# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# p1 = Product.create(category: "Body Butter", scent: "Lavender")
# p2 = Product.create(category: "Body Butter", scent: "Sweet Orange Mango")
# p3 = Product.create(category: "Body Butter", scent: "Grapefruit & Orange")
# p4 = Product.create(category: "Body Butter", scent: "Coconut & Vanilla")
# p5 = Product.create(category: "Body Butter", scent: "Oatmeal Cookie")
# p6 = Product.create(category: "Body Butter", scent: "Rose & Vanilla")

bubble_candle_1 = BubbleCandle.create(scent: "Sweet Orange", color: "Tint of Orange")
bubble_candle_2 = BubbleCandle.create(scent: "Sweet Orange", color: "Plain")
bubble_candle_3 = BubbleCandle.create(scent: "Peppermint & Lemon", color: "Pastel Green")
bubble_candle_4 = BubbleCandle.create(scent: "Peppermint & Lemon", color: "Plain")
bubble_candle_5 = BubbleCandle.create(scent: "Lavender & Lemon", color: "Pastel Purple")
bubble_candle_6 = BubbleCandle.create(scent: "Lavender & Lemon", color: "Plain")
bubble_candle_7 = BubbleCandle.create(scent: "Lavender", color: "Pastel Purple")
bubble_candle_8 = BubbleCandle.create(scent: "Lavender", color: "Plain")
bubble_candle_9 = BubbleCandle.create(scent: "Coconut & Mango", color: "Tint of Orange")
bubble_candle_10 = BubbleCandle.create(scent: "Coconut & Mango", color: "Plain")
bubble_candle_11 = BubbleCandle.create(scent: "Vanilla Rose", color: "Pastel Pink")
bubble_candle_12 = BubbleCandle.create(scent: "Peppermint Vanilla", color: "Pastel Green")
bubble_candle_13 = BubbleCandle.create(scent: "Peppermint Vanilla", color: "Plain")
bubble_candle_14 = BubbleCandle.create(scent: "Warm Vanilla Kiss")
bubble_candle_15 = BubbleCandle.create(scent: "Apple Cider")
bubble_candle_16 = BubbleCandle.create(scent: "Apple Cinnamon Spice", color: "Pastel Tan")
bubble_candle_17 = BubbleCandle.create(scent: "Vanilla Latte", color: "Pastel Tan")
bubble_candle_18 = BubbleCandle.create(scent: "Vanilla Latte", color: "Plain")
bubble_candle_19 = BubbleCandle.create(scent: "Brown Sugar Plum")
bubble_candle_20 = BubbleCandle.create(scent: "Cinnamon Pumpkin Pie")
bubble_candle_21 = BubbleCandle.create(scent: "Pumpkin & Vanilla")
bubble_candle_22 = BubbleCandle.create(scent: "Gingerbread", color: "Pastel Tan")
bubble_candle_23 = BubbleCandle.create(scent: "Gingerbread", color: "Plain")
bubble_candle_24 = BubbleCandle.create(scent: "Pumpkin Spice Latte", color: "Tint of Orange")
bubble_candle_25 = BubbleCandle.create(scent: "Pumpkin Spice Latte", color: "Plain")

boby_butter1 = BodyButter.create(scent: "Lavender")
boby_butter2 = BodyButter.create(scent: "Sweet Orange Mango")
boby_butter3 = BodyButter.create(scent: "Grapefruit & Orange")
boby_butter4 = BodyButter.create(scent: "Coconut & Vanilla")
boby_butter5 = BodyButter.create(scent: "Oatmeal Cookie")
boby_butter6 = BodyButter.create(scent: "Rose & Vanilla")